# Generated by Django 5.2.4 on 2026-02-13 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom API')], default='openai', max_length=20)),
                ('api_endpoint', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(max_length=500)),
                ('framework', models.CharField(choices=[('playwright', 'Playwright'), ('selenium', 'Selenium')], default='playwright', max_length=20)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('csharp', 'C#')], default='python', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_projects', to=settings.AUTH_USER_MODEL)),
                ('llm_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_projects', to='testgen.llmprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=80)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=10)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_key', models.TextField(blank=True, null=True)),
                ('environment_vars', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_configs', to='testgen.testproject')),
            ],
            options={
                'ordering': ['test_project', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_description', models.TextField(blank=True)),
                ('test_code', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('llm_prompt', models.TextField(blank=True)),
                ('llm_response', models.TextField(blank=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tests', to='testgen.testproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CICDPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github_actions', 'GitHub Actions'), ('gitlab_ci', 'GitLab CI'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI')], default='github_actions', max_length=20)),
                ('config_content', models.TextField()),
                ('file_path', models.CharField(max_length=255)),
                ('cron_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('on_push', models.BooleanField(default=True)),
                ('on_pull_request', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cicd_pipeline', to='testgen.testproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
