# Generated by Django 5.2.4 on 2025-08-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocktype',
            old_name='base_price_per_sqft',
            new_name='price_per_sqft',
        ),
        migrations.AddField(
            model_name='blockinstance',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blockinstance',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='blockinstance',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='blockinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='calculator.project'),
        ),
        migrations.AlterField(
            model_name='blockinstance',
            name='width',
            field=models.FloatField(),
        ),
    ]
